export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const SIGN_UP_RESET = 'SIGN_UP_RESET';

export const SMS_CONFIRM_START = 'SMS_CONFIRM_START';
export const SMS_CONFIRM_SUCCESS = 'SMS_CONFIRM_SUCCESS';
export const SMS_CONFIRM_FAILURE = 'SMS_CONFIRM_FAILURE';
export const SMS_CONFIRM_RESET = 'SMS_CONFIRM_RESET';
